version: "3.9"

services:
  client_db:
    build:
      context: .
      dockerfile: ./client_service/client_db.dockerfile
    restart: always
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "5432:5432"
  client_service:
    build:
      context: .
      dockerfile: ./client_service/client_service.dockerfile
    environment:
      POSTGRES_URL: "postgres://${DB_USER}:${DB_PASSWORD}@client_db:5432/${DB_NAME}"
      PRIVATE_KEY_PATH: "crypto/signature.pem"
      PUBLIC_KEY_PATH: "crypto/signature.pub"
    ports:
      - "8080:8080"
    depends_on:
      - client_db
